# Generated by Django 4.2.9 on 2024-02-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_deployment_edge_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="panel_link",
        ),
        migrations.AddField(
            model_name="device",
            name="table_link",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="timeseries_link",
            field=models.CharField(default="", max_length=100),
        ),
    ]
