# Generated by Django 4.2.9 on 2024-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_device_panel_link_device_table_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="categories_field",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="device",
            name="is_actionable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="is_categoric",
            field=models.BooleanField(default=None),
        ),
    ]
