# Generated by Django 4.2.9 on 2024-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_device_categories_field_device_is_actionable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="categories_field",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
