# Generated by Django 4.2.9 on 2024-03-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_device_categories_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="categories_field",
        ),
        migrations.RemoveField(
            model_name="device",
            name="is_actionable",
        ),
        migrations.RemoveField(
            model_name="device",
            name="is_categoric",
        ),
    ]
