# Generated by Django 4.2.9 on 2024-03-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_device_categories_field_device_is_actionable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="is_categoric",
            new_name="is_categorical",
        ),
    ]
