# Generated by Django 4.2.9 on 2024-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_is_categoric_device_is_categorical"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="size",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
