# Generated by Django 4.2.9 on 2024-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_device_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="server_url",
            field=models.CharField(default="http://localhost:8080", max_length=100),
        ),
    ]
