#!/bin/bash

# Setting up COMPSs_HOME
if [ -z "${COMPSS_HOME}" ]; then
  COMPSS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )/"
fi
if [ ! "${COMPSS_HOME: -1}" = "/" ]; then
  COMPSS_HOME="${COMPSS_HOME}/"
fi
export COMPSS_HOME=${COMPSS_HOME}

# Load auxiliar scripts

# shellcheck source=../system/commons/logger.sh"
# shellcheck disable=SC1091
source "${COMPSS_HOME}Runtime/scripts/system/commons/logger.sh"

# shellcheck source=../system/commons/version.sh"
# shellcheck disable=SC1091
source "${COMPSS_HOME}Runtime/scripts/system/commons/version.sh"


# shellcheck source=../system/agents/commons.sh"
# shellcheck disable=SC1091
source "${COMPSS_HOME}Runtime/scripts/system/agents/commons.sh"


###############################################
# SCRIPT CONSTANTS DECLARATION
###############################################
APP_CMD="curl"

###############################################
# ERROR CONSTANTS DECLARATION
###############################################
ERROR_MISSSING_HOST="ERROR: Indicate host and port"

if [ $# == 0 ]; then
    display_error "${ERROR_MISSSING_HOST}"
    exit 1
fi

curl -XGET "http://${1}:46101/COMPSs/resources" 2>/dev/null | jq
