FROM python:3.10

COPY ./userInterface/ /app/

RUN apt-get update && apt-get install -y jq

WORKDIR /app/
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/scripts
RUN chmod +x run_user_interface.sh

CMD ["./run_user_interface.sh"]

