#!/bin/bash


/opt/COMPSs/Runtime/scripts/user/compss_agent_start --hostname=${AGENT_NAME} --rest_port=${REST_AGENT_PORT} --comm_port=${COMM_AGENT_PORT} --project=${PROJECT_PATH} &
AGENT_PID=$!

sleep 10

curl -s -XPUT http://127.0.0.1:${REST_AGENT_PORT}/COMPSs/startApplication -H "content-type: application/xml" -d \
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
  <startApplication>
    <lang>JAVA</lang>
    <ceiClass>es.bsc.hp2c.HP2CServerItf</ceiClass>

    <className>es.bsc.hp2c.HP2CServer</className>
    <hasResult>false</hasResult>
    <methodName>main</methodName>

    <parameters>
      <params paramId=\"0\">
        <direction>IN</direction>
        <paramName>args</paramName>
        <prefix></prefix>
        <contentType></contentType>
        <stdIOStream>UNSPECIFIED</stdIOStream>
        <type>OBJECT_T</type>
        <array paramId=\"0\">
          <componentClassname>java.lang.String</componentClassname>
          <values>
          </values>
        </array>
      </params>
    </parameters>
  </startApplication>"

wait ${AGENT_PID}
