# Generated by Django 5.0.1 on 2024-02-12 16:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="sensor_type",
        ),
        migrations.AddField(
            model_name="edge",
            name="last_update",
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.CreateModel(
            name="SensorValueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.sensor",
                    ),
                ),
            ],
        ),
    ]
