# Generated by Django 5.0.1 on 2024-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="uid",
            field=models.CharField(default="", max_length=100),
        ),
    ]
