# Generated by Django 5.0.1 on 2024-02-13 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_remove_sensor_sensor_type_edge_last_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 13, 10, 11, 0, 124734)
            ),
        ),
    ]
