# Generated by Django 5.0.1 on 2024-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_deployment_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="uid",
            field=models.CharField(max_length=100),
        ),
    ]
