# Generated by Django 5.0.1 on 2024-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_deployment_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="dashboard_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="uid",
            field=models.CharField(default="", max_length=100),
        ),
    ]
