# Generated by Django 5.0.1 on 2024-02-13 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_edge_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
