#!/bin/bash

# Initialization
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
broker_config="${SCRIPT_DIR}/../20-main-simple.conf"

# Run container
docker run \
    -it --rm \
    --name hp2c_broker \
    --hostname hp2c_broker \
    -p 5672:5672 \
    -p 15672:15672 \
    -v ${broker_config}:/etc/rabbitmq/conf.d/20-main-simple.conf \
    hp2c/broker:latest
