#!/bin/bash

##
## This approach does not work unless modifying docker iptables rules 
##

# Create network with subnet to deploy containers in a specific IP
docker network create --subnet=10.0.0.0/24 hp2c-brokers-server
docker network create --subnet=10.0.1.0/24 hp2c-brokers-1

# Deploy RabbitMQ containers
docker run -d --rm \
    --name hp2c_broker_server \
    --hostname hp2c_broker_server \
    --net hp2c-brokers-server --ip 10.0.0.100 \
    -p 8081:15672 \
    --add-host "hp2c_broker_1:10.0.1.100" \
    hp2c/broker:latest
docker run -d --rm \
    --name hp2c_broker_1 \
    --hostname hp2c_broker_1 \
    --net hp2c-brokers-1 --ip 10.0.1.100 \
    -p 8082:15672 \
    --add-host "hp2c_broker_server:10.0.0.100" \
    hp2c/broker:latest

# End sequence
docker wait hp2c_broker_server
docker wait hp2c_broker_1
docker network remove hp2c-brokers-server
docker network remove hp2c-brokers-1