#!/bin/bash

# Configuration
CFG_FILE="20-main-simple.conf"
MAIN_MQ_PORT=8005
MANAGEMEN_MQ_PORT=8015
ERL_EPMD_PORT=8069
RABBITMQ_DIST_PORT=8025

# Initialization
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
broker_config="${SCRIPT_DIR}/../${CFG_FILE}"

# Auxiliar functions
on_exit(){
    echo "Clearing deployment"
    echo "Removing containers"
    docker stop hp2c_broker
}
trap 'on_exit' EXIT

wait_containers(){
    docker wait hp2c_broker
}

echo "Deploying container for BROKER (SIMPLE)"

# Run container
docker run \
    -d --rm \
    --name hp2c_broker \
    --hostname hp2c_broker \
    -p ${MAIN_MQ_PORT}:${MAIN_MQ_PORT} \
    -p ${MANAGEMEN_MQ_PORT}:${MANAGEMEN_MQ_PORT} \
    -v ${broker_config}:/etc/rabbitmq/conf.d/${CFG_FILE} \
    -e ERL_EPMD_PORT=${ERL_EPMD_PORT} \
    -e RABBITMQ_DIST_PORT=${RABBITMQ_DIST_PORT} \
    hp2c/broker:latest

echo "Testbed properly deployed"
wait_containers
echo "Ended properly"
